// FUNÇÃO RESPONSÁVEL POR VALIDAR SE TODOS OS CAMPOS FORAM PREENCHIDOS COM SUCESSO
function ValidarCampos() {}

// FUNÇÃO PARA SALVAR DADOS DE CADASTRO DENTRO DO LOCALSTORAGE
function SalvarDados() {}

// APÓS A VALIDAÇÃO DOS CAMPOS, ESSA FUNÇÃO IRÁ CADASTRAR AS INFORMAÇÕES DENTRO DO LOCALSTORAGE
function Cadastrar() {}

